# Generated by Django 4.0.3 on 2022-06-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_automobilevo_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='sold',
            field=models.CharField(default='False', max_length=8),
        ),
    ]
