# Generated by Django 4.0.3 on 2022-06-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_alter_service_date_alter_service_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.TimeField(max_length=20),
        ),
    ]
