# Generated by Django 4.0.3 on 2022-06-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_service_is_finished_alter_service_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='is_finished',
        ),
    ]
