# Generated by Django 4.0.3 on 2022-06-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_remove_service_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
