# Generated by Django 4.0.3 on 2022-06-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_rest', '0002_automobile_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobile',
            name='sold',
            field=models.CharField(default='False', max_length=8),
        ),
    ]
